### ISSUE TITLE
The Css::component option that allows for component creation

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#642]
Syntax:

```java
Css.generateStyleSheet(
  Css.component("carbon-grid", """
  mx-auto grid w-full max-w-screen-max grid-cols-4
  px-0px
  md:grid-cols-8 md:px-16px
  lg:grid-cols-16
  max:px-24px
  *:mx-16px
  """)
);
```

Should generate:

```css
.carbon-grid {
  margin-right: auto;
  margin-left: auto;
  ...
}

@media (min-width: foo) {
  .carbon-grid {
    ...
  }
}
```
