### ISSUE TITLE
css: automatic element descendant variant

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos.way#772]
For example, the following class:

```java
className("tr:background-color:neutral-100");
```

Should generate:

```css
tr\:background\:neutral-100 tr { background-color: var(--color-neutral-100) }
```
